server:
  port: 9006
spring:
  application:
    name: sms
  rabbitmq:
    host: 192.168.237.128
    port: 5672
    username: liurushan
    password: 138687
    virtual-host: /
sms:
  appcode: f795b1d600594ec684734c02c0bf62f9  #使用自己的AppCode
  tpl_id: TP1711063    # 默认模板